apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    editable: false
    jsonData:
      host: clickhouse
      port: 8123
      username: default
      defaultDatabase: default
      protocol: http
      secure: false
    secureJsonData:
      password: test123
